# Should the debug messages be send in the chat?
debug: true

# How long should we wait between weather changes? (seconds)
weather-change-delay: 60

# Message to show when the player is killed by hail
# PLAYER (all caps) will be replaced with the player name
hail-death-message: "&fPLAYER has been killed by &7Hail"

# How much the wind should push the player. You should try numbers between 0.00 and 1.00
wind-push-factor: 0.1

# *****************************************************************
# ********** How long each weather should last (seconds) **********
clear-duration: 60
hail-duration: 60

light-rain-duration: 60
heavy-rain-duration: 60

light-wind-duration: 60
heavy-wind-duration: 60

light-snow-duration: 60
heavy-snow-duration: 60

light-wind-light-rain-duration: 60  # Wind and Rain
heavy-wind-light-rain-duration: 60  # Heavy Wind and Rain
heavy-wind-heavy-rain-duration: 60  # Thunderstorm

light-wind-light-snow-duration: 60  # Wind and Snow
heavy-wind-heavy-snow-duration: 60  # Blizzard

# **********************************************************************************************
# ********** Broadcast messages. If empty, no message will be broadcast to the server **********
clear-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oThe weather has cleared up."
hail-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oHail has started to fall from the sky. Get under cover!"

light-rain-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oRain has begun to fall from the sky"
heavy-rain-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oHeavy Rain has begun to pour from the sky"

light-wind-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oWind has begun to tug at your pelt"
heavy-wind-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oA Heavy Wind has whipped up "

light-snow-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oPretty white snowflakes begun falling from the sky"
heavy-snow-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oHeavy snow begins to fall from the sky"

light-wind-light-rain-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oRain has begun pouring down. The wind is whipping it right into your face"
heavy-wind-light-rain-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oHeavy Rain has begun pouring down. The wind is whipping it right into your face"
heavy-wind-heavy-rain-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oThunder rumbles overhead… It seems a thunderstorm is rolling in"

light-wind-light-snow-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oSnow falls from the sky, hitting you in the face"
heavy-wind-heavy-snow-message: "&0[&8&lW&7&lo&f&lW&7&lS&0] &7&oHeavy Snow is swirling all around, A blizzard is occuring!"

# *******************************************************************************
# ********** How many seconds between hail damage hits and wind pushes **********
hail-delay: 5
light-wind-delay: 15
heavy-wind-delay: 20

# ******************************************************************
# ********** How many seconds to perform the given effect **********
hail-effect-duration: 1
light-wind-effect-duration: 3
heavy-wind-effect-duration: 5