# Should the debug messages be send in the chat?
debug: true

# Message to show when the player is killed by hail
# PLAYER (all caps) will be replaced with the player name
hail-death-message: "&fPLAYER has been killed by &7Hail"

# How long each weather should last (seconds)
clear-duration: 60
hail-duration: 60
light-rain-duration: 60
light-wind-duration: 60
light-windyrain-duration: 60
heavy-rain-duration: 60
heavy-wind-duration: 60
heavy-windyrain-duration: 60

# How many seconds between hail damage hits and wind pushes
hail-delay: 5
light-wind-delay: 1
heavy-wind-delay: 5
light-windyrain-delay: 5
heavy-windyrain-delay: 5

# How much the wind should push the player. You should try numbers between 0.00 and 1.00
wind-push-factor: 0.1

# The first weather change will happen randomly after the server loads the plugin
# Here you can define the range of when the first weather change will happen
# Default Minecraft weather is in the range [min=300, max=900]
weather-change-min-seconds: 5
weather-change-max-seconds: 10