# Should the debug messages be displayed in the log and chat?
debug: true

# *** How long each weather should last (seconds) ***
clear-duration: 10
hail-duration: 10
light-rain-duration: 10
light-wind-duration: 10
light-windyrain-duration: 10
heavy-rain-duration: 10
heavy-wind-duration: 10
heavy-windyrain-duration: 10

# How many seconds between hail damage hits, wind pushes
hail-delay: 2
light-wind-delay: 3
heavy-wind-delay: 3
light-windyrain-delay: 3
heavy-windyrain-delay: 3

# The first weather change will happen randomly after the server loads the plugin
# Here you can define the range of when the first weather change will happen
# Default Minecraft weather is in the range [min=300, max=900]
weather-change-min-seconds: 5
weather-change-max-seconds: 10