name: BetterWeather
main: io.github.developerjose.betterweather.BetterWeatherPlugin
author: DeveloperJose
version: 1.0
api-version: 1.13
commands:
  bweather:
    description: Handles all BetterWeather commands
    usage: /bweather help - To see a list of available commands